# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GoferTransport-http
version:      1.014
version_from: 
installdirs:  site
requires:
    Apache::Util:                  0
    DBI:                           1.56
    HTTP::Request:                 0
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
